console.log("string == string")
console.log("number == int or float")
console.log("boolean == boolean")
console.log("array == array")
console.log("object == object")
console.log("function == function")
console.log("undefined == undefined")
console.log("null == null")
console.log("void == void")
console.log("never == never")
